# Generated by Django 2.0.6 on 2018-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_ru', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('tip', models.CharField(max_length=20)),
                ('descript', models.CharField(max_length=20)),
                ('prim', models.CharField(max_length=20)),
                ('vlan_byfly', models.CharField(max_length=20)),
                ('pool_iptv', models.CharField(max_length=20)),
                ('pool_tr069', models.CharField(max_length=20)),
                ('ims_relay', models.CharField(max_length=20)),
                ('hw_access', models.CharField(max_length=20)),
                ('ohr_dhcp', models.CharField(max_length=20)),
                ('imssignaling', models.CharField(max_length=20)),
                ('imsmedia', models.CharField(max_length=20)),
                ('numbers', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
