# Generated by Django 2.0.6 on 2018-06-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmipimsstatic',
            name='prim2',
        ),
    ]
